UI/pos_tagger/pos/pos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tagger_v0/', include(('tagger_v0.urls', 'tagger_v0'), namespace="tagger_v0")),
    path('admin/', admin.site.urls),
]

UI/pos_tagger/pos/tagger_v0/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/', views.tag, name='tag'),
]

UI/pos_tagger/pos/tagger_v0/models.py
from django.db import models

# Create your models here.

UI/pos_tagger/pos/tagger_v0/views.py
import pickle
import os
import sys

from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt


module_dir = os.path.dirname(__file__)
file_path = os.path.join(module_dir, 'knowledge_base/POS_TAGGER.pickle')

sys.path.append('./tagger_v0/knowledge_base/')


with open(file_path, 'rb') as trained_model:
    trained_hmm = pickle.load(trained_model)
    hmm = trained_hmm['trained_hmm']


def index(request):
    return render(request, 'tagger_v0/index.html')


@csrf_exempt
def tag(request):
    sentence = request.POST.get('sentence', '').lower()
    sentence = sentence.split(' ')

    predicted_tags = hmm.viterbi(sentence)
    predicted_tags = '\n'.join(
        [
            f'{item} ({tag})'
            for item, tag in zip(sentence, predicted_tags)
        ]
    )

    return JsonResponse(
        {'result': predicted_tags}
    )

UI/pos_tagger/pos/tagger_v0/templates/tagger_v0/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Tagger V0</title>
        <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    </head>
    <body>
        <h4>This is a HMM(Hidden Markov Model)-trained POS(Part Of Speech) tagger trained with the MLE(Maximum Likelihood Estimation) approach, and the Brown Corpus data.</h4>

        <form id="input-form">
            {% csrf_token %}
            <textarea id="sentence" name="sentence" rows="8" cols="55" placeholder="Provide a sentence .">Fishes do not fly under most circumstances .</textarea>
            <input type="submit" value="Submit">
        </form>

        <h4 id="result" style="color: forestgreen">Result will be displayed here</h4>
        <br/>

        <pre>
            <b>tag|description|example</b>

            .|sentence closer|. ; ? !
            (|left paren|nan
            )|right paren|nan
            *|not, n't|nan
            --|dash|nan
            ,|comma|nan
            :|colon|nan

            ABL|pre-qualifier|quite, rather
            ABN|pre-quantifier|half, all
            ABX|pre-quantifier|both
            AP|post-determiner|many, several, next
            AT|article|a, the, no
            BE|be|nan
            BED|were|nan
            BEDZ|was|nan
            BEG|being|nan
            BEM|am|nan
            BEN|been|nan
            BER|are, art|nan
            BEZ|is|nan
            CC|coordinating conjunction|and, or
            CD|cardinal numeral|one, two, 2, etc.
            CS|subordinating conjunction|if, although
            DO|do|nan
            DOD|did|nan
            DOZ|does|nan
            DT|singular determiner|this, that
            DTI|singular or plural determiner/quantifier|some, any
            DTS|plural determiner|these, those
            DTX|determiner/double conjunction|either
            EX|existential there|nan
            FW|foreign word (hyphenated before regular tag)|nan
            HL|word occurring in headline (hyphenated after regular tag)|nan
            HV|have|nan
            HVD|had (past tense)|nan
            HVG|having|nan
            HVN|had (past participle)|nan
            HVZ|has|nan
            IN|preposition|nan
            JJ|adjective|nan
            JJR|comparative adjective|nan
            JJS|semantically superlative adjective| chief, top
            JJT|morphologically superlative adjective|biggest
            MD|modal auxiliary|can, should, will
            NC|cited word (hyphenated after regular tag)|nan
            NN|singular or mass noun|nan
            NN$|possessive singular noun|nan
            NNS|plural noun|nan
            NNS$|possessive plural noun|nan
            NP|proper noun or part of name phrase|nan
            NP$|possessive proper noun|nan
            NPS|plural proper noun|nan
            NPS$|possessive plural proper noun|nan
            NR|adverbial noun|home, today, west
            NRS|plural adverbial noun|nan
            OD|ordinal numeral|first, 2nd
            PN|nominal pronoun|everybody, nothing
            PN$|possessive nominal pronoun|nan
            PP$|possessive personal pronoun|my, our
            PP$$|second (nominal) possessive pronoun|mine, ours
            PPL|singular reflexive/intensive personal pronoun|myself
            PPLS|plural reflexive/intensive personal pronoun|ourselves
            PPO|objective personal pronoun|me, him, it, them
            PPS|3rd. singular nominative pronoun|he, she, it, one
            PPSS|other nominative personal pronoun|I, we, they, you
            QL|qualifier|very, fairly
            QLP|post-qualifier|enough, indeed
            RB|adverb|nan
            RBR|comparative adverb|nan
            RBT|superlative adverb|nan
            RN|nominal adverb|here then, indoors|nan
            RP|adverb/particle|about, off, up
            TL|word occurring in title (hyphenated after regular tag)|nan
            TO|infinitive marker to|nan
            UH|interjection, exclamation|nan
            VB|verb, base form|nan
            VBD|verb, past tense|nan
            VBG|verb, present participle/gerund|nan
            VBN|verb, past participle|nan
            VBZ|verb, 3rd. singular present|nan
            WDT|wh- determiner|what, which
            WP$|possessive wh- pronoun|whose
            WPO|objective wh- pronoun|whom, which, that
            WPS|nominative wh- pronoun|who, which, that
            WQL|wh- qualifier|how
            WRB|wh- adverb|how, where, when
        </pre>
    </body>

    <script>
        $("#input-form").submit(function(e){
            var sentence = $('#sentence').val()
            if (sentence.length < 1)
                alert('Empty Sentence !!!')
            else {
                $('#result').text('The tagging is in the process !!!')

                $.ajax({
                    type: "POST",
                    url: "{% url 'tagger_v0:tag' %}",
                    data: {'sentence': sentence},
                    success: function(result){
                        $('#result').text(result['result'])
                    }
                })
            }

            e.preventDefault()
        });
    </script>
</html>